### ISSUE TITLE
Missing prerequisite steps?

### ISSUE THREAD

**Issue by lgroner** [Alescontrela/Numpy-CNN#1]
In a windows 10 environment, following instructions, in a dos command prompt window I typed:

  pip install -r requirements.txt
The response was 
  Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Clearly I a missing something. Any ideas?

**Comment by escontra** [comment]
Hi @lgroner ,

That's strange. Are you sure you cloned the repo correctly? If you look at the repo's main directory, you'll notice a `requirements.txt` file. Also, make sure you navigate into the cloned repository before running the pip install command.

**Comment by lgroner** [comment]
Thank you. Your response got me past the last problem to the next glitch.

C:\Users\user\Documents\GitHub\Numpy-CNN>pip install -r requirements.txt
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1)) (1.12.1)
Collecting tqdm (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/93/24/6ab1df969db228aed36a648a8959d1027099ce45fad67532b9673d533318/tqdm-4.23.4-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 516kB/s
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: python-dateutil in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: six>=1.10 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.10.0)
Requirement already satisfied: pytz in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (2017.2)
Installing collected packages: tqdm
  The script tqdm.exe is installed in 'c:\users\user\appdata\local\programs\python\python36-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed tqdm-4.23.4

I did add this directory to the path.

However, running:
   from CNN.network import *
I get:
============= RESTART: F:\Ed\EdPython\PythonScripts\numpyLHG.py =============
Traceback (most recent call last):
  File "F:\Ed\EdPython\PythonScripts\numpyLHG.py", line 8, in <module>
    from CNN.network import *
ModuleNotFoundError: No module named 'CNN'

Ideas?

**Comment by escontra** [comment]
Again, make sure that the /CNN directory is in the same folder as the script you've created. 

Closing this issue as this is not a problem with the repository.
