### ISSUE TITLE
last dense layer outputs are blowing up, making softmax values to nan 

### ISSUE THREAD

**Issue by jahnavi-7** [Alescontrela/Numpy-CNN#3]
Need some suggestions on how to resolve this problem.

**Comment by adeeb2809** [comment]
Hey,
Have you been able to resolve this issue? 
I'm having the same problem
Thks in advance

**Comment by jahnavi-7** [comment]
Hi,
Yes, I have resolved the issue by normalizing the outputs of the last dense
layer and then I passed the normalized values to softmax.

**Comment by adeeb2809** [comment]
Thanks. I'll try it and see if it works.

**Comment by adeeb2809** [comment]
Hi,
I have not been able to resolve the problem.
Can you kindly send me the part of the code where you normalized the
outputs of the last dense layer.

Thanks
